Needs review: Change date casting
The following line of code in 2 models causes the error below.

`cast((event_id / 864000) - 21550 as datetime) as datetime2(0)`

Error: `Explicit conversion from data type numeric to datetime2 is not allowed`

This is fixed by casting to char(8) instead of datetime.
@quindavies to review.